-- CreateTable
CREATE TABLE "Partidos" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "rival" TEXT NOT NULL,
    "fecha" DATETIME NOT NULL,
    "cancha" INTEGER NOT NULL
);

-- CreateTable
CREATE TABLE "Borrachos" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "dni" INTEGER NOT NULL,
    "nombre" TEXT NOT NULL,
    "usuario" TEXT NOT NULL,
    "contrasena" TEXT NOT NULL,
    "cuota" INTEGER NOT NULL
);

-- CreateTable
CREATE TABLE "_PARTIDOS_X_BORRACHOS" (
    "A" INTEGER NOT NULL,
    "B" INTEGER NOT NULL,
    CONSTRAINT "_PARTIDOS_X_BORRACHOS_A_fkey" FOREIGN KEY ("A") REFERENCES "Borrachos" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "_PARTIDOS_X_BORRACHOS_B_fkey" FOREIGN KEY ("B") REFERENCES "Partidos" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "Borrachos_dni_key" ON "Borrachos"("dni");

-- CreateIndex
CREATE UNIQUE INDEX "_PARTIDOS_X_BORRACHOS_AB_unique" ON "_PARTIDOS_X_BORRACHOS"("A", "B");

-- CreateIndex
CREATE INDEX "_PARTIDOS_X_BORRACHOS_B_index" ON "_PARTIDOS_X_BORRACHOS"("B");
